version: '3'

volumes:
  dbdata:
  searchdata:

services:
  web:
    build: containers/web
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html:cached
    depends_on:
      - db
      - search
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
  search:
    build: containers/search
    restart: always
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - searchdata:/usr/share/elasticsearch/data
