version: '3'

volumes:
  dbdata:
  searchdata:

services:
  web:
    build: containers/web
    ports:
      - 80:80
    links:
      - db
      - search
    volumes:
      - ./src:/var/www/html
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
  search:
    build: containers/search
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - searchdata:/usr/share/elasticsearch/data
