version: '3'

volumes:
  datastore:
    driver: 'local'

services:
  web:
    build: containers/web
    ports:
      - 80:80
    links:
      - db
      - search
    volumes:
      - ./src:/var/www/html
  db:
    build: containers/db
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - datastore:/var/lib/mysql
  search:
    build: containers/search
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - datastore:/usr/share/elasticsearch/data
